### ISSUE TITLE
Add files to bytedeco/sample-projects

### ISSUE THREAD

**Issue by saudet** [piersy/BasicTesseractExample#1]
This sample project looks like a perfect candidate for the collection I'm trying to build at https://github.com/bytedeco/sample-projects. Please consider sending a pull request. Thank you!

**Comment by krishnapank** [comment]
Getting below error while maven build

Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnilept in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1878)
    at java.lang.Runtime.loadLibrary0(Runtime.java:849)
    at java.lang.System.loadLibrary(System.java:1087)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:536)
    at org.bytedeco.javacpp.Loader.load(Loader.java:411)
    at org.bytedeco.javacpp.Loader.load(Loader.java:354)
    at org.bytedeco.javacpp.lept.<clinit>(lept.java:10)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:270)
    at org.bytedeco.javacpp.Loader.load(Loader.java:386)
    at org.bytedeco.javacpp.Loader.load(Loader.java:354)
    at org.bytedeco.javacpp.tesseract$TessBaseAPI.<clinit>(tesseract.java:3422)
    at BasicTesseractExampleTest.main(BasicTesseractExampleTest.java:14)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/javacpp2676635435843/libjnilept.so: libjbig.so.2.1: cannot open shared object file: No such file or directory
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1957)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1882)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1843)
    at java.lang.Runtime.load0(Runtime.java:795)
    at java.lang.System.load(System.java:1061)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:525)
    ... 9 more

**Comment by saudet** [comment]
So, please fix it and send a pull request to my repository, thanks!

**Comment by Purushotham230** [comment]
![2](https://user-images.githubusercontent.com/45062964/112277190-7f69cf80-8ca7-11eb-8045-4f5ed8cf3ee6.png)
It's working fine for an image having quotes or poems but unable to read grid tabe data, is there any way to read grid table data or am I missing something ?

OCR output:
o e oww  fowes e
P s e [veomen v s
e [ [womms o e
T lowems  Jwmmen [woomnn e e
T e o wcomes e
P ew e lowonies Jomemmems |
